# This is a basic workflow to help you get started with Actions

name: build-nightly

# Controls when the workflow will run
on:
  schedule:
    - cron: "0 3 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          repository: NationalSecurityAgency/ghidra
      
      - name: Cache
        uses: actions/cache@v3.0.4
        with:
          # A list of files, directories, and wildcard patterns to cache and restore
          path: dependencies
          # An explicit key for restoring and saving the cache
          key: ghidra-dependencies

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          gradle -I gradle/support/fetchDependencies.gradle init
          gradle buildGhidra
          
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          path: build/dist/*.zip
          
