# This is a basic workflow to help you get started with Actions

name: build-nightly

# Controls when the workflow will run
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 3 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    strategy:
      matrix:
        os: [windows-latest]
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          repository: NationalSecurityAgency/ghidra

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
          java-package: jdk # optional (jdk, jre, jdk+fx or jre+fx) - defaults to jdk
          check-latest: true
          cache: 'gradle'
      
      - name: Cache
        uses: actions/cache@v3.0.4
        with:
          path: dependencies
          key: ghidra-dependencies

      # Runs a set of commands using the runners shell
      - name: fetch-deps
        run: |
          gradle -I gradle/support/fetchDependencies.gradle init
          
      # Runs a set of commands using the runners shell
      - name: build
        run: |
          gradle buildGhidra
          
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: artifact ${{ matrix.os }}
          path: build/dist/*.zip
          
